### ISSUE TITLE
Update aurelia to Beta 1

### ISSUE THREAD

**Issue by RainerAtSpirit** [PulsarBlow/aurelia-firebase#1]
Would it be possible to update to Beta1?

**Comment by PulsarBlow** [comment]
Hi @RainerAtSpirit 

I just published a new release with aurelia updated to 1.0.0-beta.1

**Comment by RainerAtSpirit** [comment]
Excellent

**Comment by RainerAtSpirit** [comment]
Just noticed that this broke some tests https://circleci.com/gh/PulsarBlow/aurelia-firebase/20

**Comment by PulsarBlow** [comment]
Yes, tests are working locally but not on circleci anymore. Working on it.
