### ISSUE TITLE
Futures plans for aurelia-firebase?

### ISSUE THREAD

**Issue by forest** [PulsarBlow/aurelia-firebase#5]
Hi @PulsarBlow,

Just wondering if you have plans for active development of aurelia-firebase? I'm evaluating now and wondering if it was worth my efforts to learn the code and contribute. Also wondering what you see as next in the roadmap?

Thanks,
forest

**Comment by PulsarBlow** [comment]
Hi @forest,

Yes, I have plans for active development of aurelia-firebase.
I'm just waiting for the Aurelia Release Candidate before releasing aurelia-firebase next set of features.
The Aurelia API is still evolving rapidly and i would like to be able to freeze a set of features against a stable API.

As i wrote it in the readme, next in the roadmap are : 
- Firebase object sync
- Firebase Query support
- Firebase Transactions support
