### ISSUE TITLE
Third party authentications

### ISSUE THREAD

**Issue by TheoMer** [PulsarBlow/aurelia-firebase#6]
Is there an eta for this feature yet?

**Comment by PulsarBlow** [comment]
Hi @TheoMer ,

This feature was initialy planned to be released upon the completion of others core Firebase features like Query support and Transactions.

But this isn't a lot of work so i could try to release that in the next version.
Don't hesitate to open a PR on that if you want to contribute.

/Cheers

**Comment by TheoMer** [comment]
Excellent.
